### ISSUE TITLE
proper check for filename before calling subprocess

### ISSUE THREAD

**Issue by prakhar2b** [RaRe-Technologies/gensim#1485]
Based on discussion [here](https://groups.google.com/forum/#!topic/gensim/nKVWoftW71Q), we should properly check for filename before `process calls` in `utils.check-output()`, and raise more intuitive exception and error message.

cc @jayantj

**Comment by tmylk** [comment]
@averages A tutorial to get started is in https://github.com/RaRe-Technologies/gensim/blob/develop/docs/notebooks/FastText_Tutorial.ipynb

**Comment by tmylk** [comment]
The KeyboardInterrupt handling can probably be removed as it was needed for 2.6 https://github.com/RaRe-Technologies/gensim/pull/1182

**Comment by tmylk** [comment]
The cpython `check_output` code https://github.com/python/cpython/blob/master/Lib/subprocess.py

**Comment by AverageS** [comment]
@tmylk @prakhar2b 
https://github.com/RaRe-Technologies/gensim/pull/1501 
It should fix the problem

**Comment by pratikmjoshi** [comment]
@menshikh-iv Can I go ahead with this?

**Comment by menshikh-iv** [comment]
@pratikmjoshi of course

**Comment by pratikmjoshi** [comment]
@menshikh-iv Just to clarify, fix #1501 did not solve this issue, right? Am I supposed to add an exception and error message for an incorrect filepath to the FastText directory, and should it indicate that the path be changed to the executable? What should the error message look like?

**Comment by menshikh-iv** [comment]
@pratikmjoshi #1501 solved this issue, but partially
- the solution should work on main OS system (Linux, MacOSX, Windows)
- the idea is simple, before running anything, check that this path exists & executable

**Comment by pratikmjoshi** [comment]
@menshikh-iv Sorry, but I've been getting a bit confused with the code. In utils.py, is a function like this for path checking ok? The code is basically from #1501 , but I've added a check for amending the path depending on the platform. What will be the Windows equivalent of /usr/bin/ (I've just put C:\\Users\\ ,pretty sure that its incorrect)? Am I missing anything else?

![screenshot from 2018-03-06 04-27-08](https://user-images.githubusercontent.com/19923446/37004589-eec5ebfe-20f6-11e8-830f-e2cc1ec91787.png)

And at check_output....

![screenshot from 2018-03-06 04-28-36](https://user-images.githubusercontent.com/19923446/37004610-fee7365a-20f6-11e8-8dad-71880e8ee762.png)

**Comment by pratikmjoshi** [comment]
@menshikh-iv  After making the necessary changes, the respective error messages are raised as below:

![screenshot from 2018-03-06 04-40-03](https://user-images.githubusercontent.com/19923446/37005066-b48bd942-20f8-11e8-9ae6-fc0f573dffbe.png)


![screenshot from 2018-03-06 04-40-17](https://user-images.githubusercontent.com/19923446/37005084-bf83f5dc-20f8-11e8-8cc7-eddf9d5ad5d4.png)

However, after entering the right path, I'm still getting this error on the notebook. Any advice?

![screenshot from 2018-03-06 04-43-02](https://user-images.githubusercontent.com/19923446/37005122-e72cac0a-20f8-11e8-8489-6429ad3f41f4.png)

![screenshot from 2018-03-06 04-43-05](https://user-images.githubusercontent.com/19923446/37005131-ed00e7cc-20f8-11e8-836c-4ee666d1c454.png)

**Comment by menshikh-iv** [comment]
@pratikmjoshi about path (`/usr/bin`, etc): they can be many varieties only on Linux + user can have some custom path, and we have not started with other OS. IMO this way doesn't look like the right way.

Also, sometimes, wappers want to path to "folder" (and have hard-coded executable), please check, how it works for all wrappers (it's not so simple).
